django/cr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('stu.urls')),
    path('admin/', admin.site.urls),
]

django/stu/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'stu'

urlpatterns = [
	url(r'^$', views.student_index, name='home'),
	url(r'^apply/(?P<job_id>[0-9]+)/(?P<stu_id>[0-9]+)/$', views.apply, name='apply'),
	url('check', views.check, name='check'),
	url(r'^company/(?P<com_name>[A-Za-z]+)$', views.company_details, name='company_details'),
	url(r'^company-home$', views.company_index, name='company_home'),
	# url(r'^company-home$', views.CompanyView.as_view(), name='company_home'),
	url(r'delete/(?P<job_id>[0-9]+)$', views.job_delete,name='delete'),
	url(r'job/add/1$', views.JobCreate.as_view(), name='job-add'),
	url(r'login$', views.login, name='login'),
	url(r'logout$', views.logout, name='logout'),
	#url is such that no one can guess it
	# url(r'login$', views.LogIn.as_view(), name='login'),
	url(r'job/added$', views.job_add, name='job-added'),


]

django/stu/models.py
from django.db import models
# from django.core.urlresolvers import reverse

# Create your models here.
class Student(models.Model):
	name = models.CharField(max_length=128, unique=False)
	email = models.CharField(max_length=128, unique=True)
	password = models.CharField(max_length=128, unique=False)
	# photo = models.ImageField(upload_to='static/images/student_images', default='static/images/favicon')

	# def get_absolute_url(self):

	def __str__(self):
		return self.name


class Company(models.Model):
	name = models.CharField(max_length=128, unique=True)
	email = models.CharField(max_length=128,unique=True)
	about = models.CharField(max_length=512, unique=False)
	password = models.CharField(max_length=128, unique=False)

	def __str__(self):
		return self.name


class Job(models.Model):
	pos = models.CharField(max_length=64, unique=False)
	company = models.ForeignKey('Company', on_delete=models.CASCADE)
	skills = models.CharField(max_length=264, unique=False)

	class Meta:
		unique_together = ('pos', 'company')

	def __str__(self):
		return "%s (%s)"%(self.pos,self.company)


class Application(models.Model):
	student_id = models.ForeignKey('Student', on_delete=models.CASCADE)
	job_id = models.ForeignKey('Job', on_delete=models.CASCADE)
	status = models.CharField(max_length=12, unique=False)

	class Meta:
		unique_together = ('student_id', 'job_id')

	def __str__(self):
		return "#%d"%(self.pk)


django/stu/views.py
from django.shortcuts import render, redirect
from stu.models import Job, Application, Company, Student
from django.http import HttpResponse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.


def student_index(request):
	# student = Student.objects.get(pk=3)
	if request.session.get('student_id','None')=='None':
		# print(request.session.get('student_id','None'))
		return redirect('stu:login')
	# print(request.session.get('student_id','None'))

	student = Student.objects.get(pk=request.session['student_id'])
	applications = student.application_set.all()
	jobs = Job.objects.all()
	applied_jobs = [a.job_id for a in applications]
	new_jobs = set(jobs).difference(applied_jobs)
	companies = Company.objects.all()
	return render(request, 'student/index.html',
				  {'student': student, 'applications': applications, 'jobs': new_jobs, 'companies': companies})


def company_details(request, com_name):
	if request.session.get('student_id',None)==None:
		return redirect('stu:login')
	student = Student.objects.get(pk=request.session['student_id'])
	company = Company.objects.get(name=com_name)
	jobs = company.job_set.all()
	applications = student.application_set.all()
	applied_jobs = [a.job_id for a in applications]
	new_jobs = set(jobs).difference(applied_jobs)
	return render(request, 'company/index.html',
				  {'student': student, 'jobs': jobs, 'new_jobs': new_jobs, 'company': company})


# return HttpResponse("Hello, world. You're at the polls index.")

def apply(request, job_id, stu_id):
	if request.session.get('student_id',None)==None:
		return redirect('stu:login')
	app = Application.objects.create(student_id=Student.objects.get(pk=stu_id), job_id=Job.objects.get(pk=job_id),
									 status='Applied')
	# print(app)
	return redirect('stu:home')


# return HttpResponse("<h3>applied</h3>")
# return redirect('stu_index')

def check(request):
	try:
		user = Student.objects.get(email=request.POST['email'])
	except Student.DoesNotExist:
		user = None

	if user!= None and user.password == request.POST['password']:
		request.session['student_id'] = user.id
		return redirect('stu:home')

	try:
		user = Company.objects.get(email=request.POST['email'])
	except Company.DoesNotExist:
		user = None

	if user!=None and user.password == request.POST['password']:
		request.session['company_id'] = user.id
		return redirect('stu:company_home')
	request.session['login_error']='incorrect credentials'
	return redirect('stu:login')
	# return redirect('stu:login')

def login(request):
	msg=''
	if request.session.get('login_error',None)!=None:
		msg=request.session.get('login_error')
		del request.session['login_error']

	return render(request, 'company/login_form.html',{'msg':msg})

def logout(request):
	# print('None')
	if type(request.session.get('student_id',None))==int:
		del request.session['student_id']
		request.session.modified = True
	if not request.session.get('company_id',None)==None:
		del request.session['company_id']
		request.session.modified = True
	return redirect('stu:login')


def company_index(request):
	if request.session.get('company_id',None)==None:
		return redirect('stu:login')
	# company = Company.objects.get(pk=2)
	company = Company.objects.get(pk=request.session['company_id'])
	jobs = company.job_set.all()
	return render(request, 'company/index.html', {'jobs': jobs})

def job_delete(request, job_id):
	if request.session.get('company_id',None)==None:
		return redirect('stu:login')

	Job.objects.filter(id=job_id).delete()
	return redirect('stu:company_home')

def job_add(request):
	if request.session.get('company_id',None)==None:
		return redirect('stu:login')

	# replace Company.objectsget(id=2) by company's session variable
	add = Job.objects.create(pos=request.POST.get('pos',''),company=Company.objects.get(id=request.session.get('company_id')),skills=request.POST.get('skills',''))
	return redirect('stu:company_home')

class JobCreate(CreateView):
	template_name = "company/job_form.html"
	model = Job
	fields = ['pos', 'skills']

# class CompanyView(generic.ListView):
# 	template_name = 'company/index.html'
# 	context_object_name = 'jobs'
# 	def get_queryset(self):
# 		company = Company.objects.get(pk=2)
# 		return company.job_set.all()

# class LogIn(CreateView):
#     template_name = "company/login_form.html"
#     model = Student
#     fields = ['name', 'email', 'photo']

django/stu/templates/company/base.html
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Campus Recruitment System</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="{% static 'images/android-desktop.jpg' %}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="{% static 'images/touch/ms-touch-icon-144x144-precomposed.png ' %}">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="{% static 'images/favicon.jpg' %}">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-red.min.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
        <div class="mdl-layou mdl-layout__header-row">
        </div>
        <section class="section mdl-layout__header-row mdl-grid mdl-grid--no-spacing">
          <!--<div class="mdl-cell mdl-cell&#45;&#45;1-col mdl-cell&#45;&#45;0-col-phone">-->
          <!--</div>-->
          <div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
              <a href="{% url 'stu:home' %}"><img id="logo" src="{% static 'images/favicon.jpg' %}"/></a>
          </div>
          <div class="mdl-cell mdl-cell--9-col mdl-cell--8-col-phone">
            <h3>Indian Institute of Information Technology Guwahati</h3>
          </div>
        </section>
        <div class="mdl-layout mdl-layout__header-row">
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-layout__tab-panel" id="faq">
           <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
            <div class="mdl-card mdl-cell mdl-cell--12-col">
                {% block body %}
                {% endblock %}
            </div>
          </section>
        </div>
      </main>
    </div>
  </body>
<!-- <script src="https://code.getmdl.io/1.3.0/material.min.js"></script> -->
<!-- <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script> -->
</html>

django/stu/templates/company/form-template.html
{% for field in form %}
<!-- <div class="mdl-textfield mdl-js-textfield"> -->
<center>
	<div class="mdl-textfield">
		<label>{{ field.label_tag }}</label>
		{{ field }}
	</div>
     <!--<input class="mdl-textfield__input" type="text" id={{field.label_tag}} name={{field.label_tag}}>-->
     <!--<label class="mdl-textfield__label" for={{field.label_tag}}>{{ field.label_tag }}</label>-->
<!-- </div> -->
</center>

{% endfor %}

django/stu/templates/company/job_form.html
{% extends 'company/base.html' %}
{% block body %}

	<form id="job-add-form" action="{% url 'stu:job-added' %}" method="POST">
	<div class="mdl-card__supporting-text">
        {% csrf_token %}
		{% include 'company/form-template.html' %}
	</div>
	<div class="mdl-card__actions">
		<!-- <a><button class="mdl-button" type="submit">Submit</button></a> -->
		<a class="mdl-button">
		<button class="mdl-button">
			Submit
		</button>
		</a>
	</div>
	</form>

{% endblock %}

django/stu/templates/company/login-form-template.html
{% for field in form %}
<!-- <div class="mdl-textfield mdl-js-textfield"> -->
<center>
	<div class="mdl-textfield">
		<label>{{ field.label_tag }}</label>
		{{ field }}
	</div>
     <!--<input class="mdl-textfield__input" type="text" id={{field.label_tag}} name={{field.label_tag}}>-->
     <!--<label class="mdl-textfield__label" for={{field.label_tag}}>{{ field.label_tag }}</label>-->
<!-- </div> -->
</center>

{% endfor %}

django/stu/templates/company/login_form.html
{% extends 'company/base.html' %}
{% block body %}
	<form id="login-form" action="{% url 'stu:check' %}" method="POST">
	<div class="mdl-card__supporting-text">
        {% csrf_token %}
		<!-- {% include 'company/login-form-template.html' %} -->
		<center>
			<p style="color: red">{{msg}}</p>
			<div class="mdl-textfield mdl-js-textfield">
				<span>
					&nbsp
				</span>
				<label class="mdl-textfield__label">Email:</label>
				<input class="mdl-textfield__input" type="email" name="email" id="email"><br/>
			</div><br>
		  	<div class="mdl-textfield mdl-js-textfield">
		  		<span>
					&nbsp
				</span>
				<label class="mdl-textfield__label">Password</label>
				<input class="mdl-textfield__input" type="password" name="password" id="password">
		  	</div>
		</center>
	</div>
	<div class="mdl-card__actions">
		<!-- <a><button class="mdl-button" type="submit">Submit</button></a> -->
		<a class="mdl-button">
			<button class="mdl-button">Log In</button>
		</a>
	</div>
	</form>
<!-- Simple Textfield -->
<form action="#">
</form>
{% endblock %}

django/stu/templates/index.html
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Campus Recruitment System</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="{% static 'images/android-desktop.jpg' %}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="{% static 'images/touch/ms-touch-icon-144x144-precomposed.png ' %}">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="{% static 'images/favicon.jpg' %}">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
          <h3>Indian Institute of Information Technology Guwahati</h3>
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark">
          <a href="#overview" class="mdl-layout__tab is-active">Dashboard</a>
          <a href="#jobs" class="mdl-layout__tab">Browse Jobs</a>
          <a href="#companies" class="mdl-layout__tab">View Companies</a>
          <!-- <a href="#features" class="mdl-layout__tab">Applied</a> -->
          <a href="#faq" class="mdl-layout__tab">FAQ</a>
          <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent" id="add">
            <i class="material-icons" role="presentation">message</i>
            <span class="visuallyhidden">Message</span>
          </button>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-layout__tab-panel is-active" id="overview">
          <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
            <div class="mdl-card mdl-cell mdl-cell--12-col">

              <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
                <h4 class="mdl-cell mdl-cell--12-col">Details</h4>
                {% for application in applications %}
                <div class="section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone">
                  <div class="section__circle-container__circle mdl-color--primary"></div>
                </div>
                <div class="section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
                  <h5>{{application.job_id.company}}</h5>
                  <!--<p>{{application.job_id.company.about}}</p>-->
                  <p><a href="#">{{application.job_id.pos}}</a>
                  <span style="float: right;"><b>Status</b>:{{application.status}}&nbsp&nbsp</span></p>
                </div>
                {% endfor %}
              </div>

              <div class="mdl-card__actions">
                  <a href="#" class="mdl-button">
                    <i class="material-icons">keyboard_arrow_down</i>
                  </a>
              </div>

            </div>
          </section>
        </div><br><br>


        <div class="mdl-layout__tab-panel" id="jobs">
          {% for job in jobs %}
          <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
            <div class="mdl-card mdl-cell mdl-cell--12-col">
              <div class="mdl-card__supporting-text">
                <h4>{{job.pos}}</h4>
                {{job.company.about}}
              </div>
              <div class="mdl-card__actions">
                <a href="#" class="mdl-button">Read More Details</a>
              </div>
            </div><br><br>
          </section>
          {% endfor%}
        </div><br><br>

         <div class="mdl-layout__tab-panel" id="companies">
           {% for company in companies %}
           <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
            <div class="mdl-card mdl-cell mdl-cell--12-col">
              <div class="mdl-card__supporting-text">
                <h4>{{company.name}}</h4>
                <p>{{company.about}}</p>
                  <ul>
                  {% for job in company.job_set.all %}
                    <li>{{job.pos}}</li>
                  {% endfor %}
                  </ul>
              </div>
               <div class="mdl-card__actions">
                   <a href="#" class="mdl-button">Read More Details</a>
              </div>
            </div>
          </section>
           {% endfor %}
         </div><br><br>
        <footer class="mdl-mega-footer">
          <div class="mdl-mega-footer--middle-section">
            <div class="mdl-mega-footer--drop-down-section">
              <input class="mdl-mega-footer--heading-checkbox" type="checkbox" checked>
              <h1 class="mdl-mega-footer--heading">Features</h1>
              <ul class="mdl-mega-footer--link-list">
                <li><a href="#">About</a></li>
                <li><a href="#">Terms</a></li>
                <li><a href="#">Partners</a></li>
                <li><a href="#">Updates</a></li>
              </ul>
            </div>
            <div class="mdl-mega-footer--drop-down-section">
              <input class="mdl-mega-footer--heading-checkbox" type="checkbox" checked>
              <h1 class="mdl-mega-footer--heading">Details</h1>
              <ul class="mdl-mega-footer--link-list">
                <li><a href="#">Spec</a></li>
                <li><a href="#">Tools</a></li>
                <li><a href="#">Resources</a></li>
              </ul>
            </div>
            <div class="mdl-mega-footer--drop-down-section">
              <input class="mdl-mega-footer--heading-checkbox" type="checkbox" checked>
              <h1 class="mdl-mega-footer--heading">Technology</h1>
              <ul class="mdl-mega-footer--link-list">
                <li><a href="#">How it works</a></li>
                <li><a href="#">Patterns</a></li>
                <li><a href="#">Usage</a></li>
                <li><a href="#">Products</a></li>
                <li><a href="#">Contracts</a></li>
              </ul>
            </div>
            <div class="mdl-mega-footer--drop-down-section">
              <input class="mdl-mega-footer--heading-checkbox" type="checkbox" checked>
              <h1 class="mdl-mega-footer--heading">FAQ</h1>
              <ul class="mdl-mega-footer--link-list">
                <li><a href="#">Questions</a></li>
                <li><a href="#">Answers</a></li>
                <li><a href="#">Contact us</a></li>
              </ul>
            </div>
          </div>
          <div class="mdl-mega-footer--bottom-section">
            <div class="mdl-logo">
              More Information
            </div>
            <ul class="mdl-mega-footer--link-list">
              <li><a href="https://developers.google.com/web/starter-kit/">Web Starter Kit</a></li>
              <li><a href="#">Help</a></li>
              <li><a href="#">Privacy and Terms</a></li>
            </ul>
          </div>
        </footer>
      </main>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>